// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Schedule/internal/dao/internal"
)

// internalKeymapDao is internal type for wrapping internal DAO implements.
type internalKeymapDao = *internal.KeymapDao

// keymapDao is the data access object for table keymap.
// You can define custom methods on it to extend its functionality as you wish.
type keymapDao struct {
	internalKeymapDao
}

var (
	// Keymap is globally public accessible object for table keymap operations.
	Keymap = keymapDao{
		internal.NewKeymapDao(),
	}
)

// Fill with you ideas below.
