// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"Schedule/internal/dao/internal"
)

// internalRouteDao is internal type for wrapping internal DAO implements.
type internalRouteDao = *internal.RouteDao

// routeDao is the data access object for table route.
// You can define custom methods on it to extend its functionality as you wish.
type routeDao struct {
	internalRouteDao
}

var (
	// Route is globally public accessible object for table route operations.
	Route = routeDao{
		internal.NewRouteDao(),
	}
)

// Fill with you ideas below.
